Assignment_ThangNVPH25980/Models/Bill.cs
namespace Assignment_ThangNVPH25980.Models
{
    public class Bill
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int Status { get; set; }
        public virtual Accounts Accounts { get; set; }
        public virtual IEnumerable<BillDetails> BillDetails { get; set; }
    }
}

Assignment_ThangNVPH25980/Models/BillDetails.cs
namespace Assignment_ThangNVPH25980.Models
{
    public class BillDetails
    {
        public Guid Id { get; set; }
        public Guid BillId { get; set; }
        public Guid ProductId { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public virtual Bill Bill { get; set; } 
        public virtual ProductDetails ProductDetails { get; set; }

    }
}

Assignment_ThangNVPH25980/Models/Cart.cs
namespace Assignment_ThangNVPH25980.Models
{
    public class Cart
    {
        public Guid UserId { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public virtual Accounts Accounts { get; set; }
        public virtual IList<CartDetails> CartDetails { get; set; }
        
    }
}

Assignment_ThangNVPH25980/Models/Products.cs
namespace Assignment_ThangNVPH25980.Models
{
    public class Products
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int Price { get; set; }
        public Guid CategoryId { get; set; }
        public int Status { get; set; }
        public virtual Category Category { get; set; }
        public virtual IList<ProductDetails> ProductDetails { get; set; }



    }
}

Assignment_ThangNVPH25980/ViewModels/CartView.cs
namespace Assignment_ThangNVPH25980.ViewModels
{
    public class CartView
    {
        public Guid ProductId { get; set; }
        public Guid UserId { get; set; }
        public string Image { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
    }
}

Assignment_ThangNVPH25980/ViewModels/ProductView.cs
namespace Assignment_ThangNVPH25980.ViewModels
{
    public class ProductView
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int Price { get; set; }
        public int AvailableQuantity { get; set; }
        public string  Size { get; set; }
        public string Color { get; set; }
        public string Category { get; set; }
        public int Status { get; set; }
    }
}

Assignment_ThangNVPH25980/Controllers/CartController.cs
using Assignment_ThangNVPH25980.IServices;
using Assignment_ThangNVPH25980.Models;
using Assignment_ThangNVPH25980.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Assignment_ThangNVPH25980.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartDetailServices cartDetailServices;
        public CartController()
        {
            cartDetailServices = new CartDetailServices();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Cart()
        {
            List<CartDetails> cartDetails = cartDetailServices.GetAllCartDetails();
            ViewBag.CartDetail = cartDetails;
            return View();
        }
        [HttpPost]
        public IActionResult Cart(Guid IdPro)
        {

            string user = HttpContext.Session.GetString("User");
            Accounts users = JsonConvert.DeserializeObject<Accounts>(user);
            List<CartDetails> cartDetails = cartDetailServices.GetAllCartDetails().Where(x => x.UserId == users.Id).ToList();

            // List<Cart> Carts =_cartService.GetAllCarts().Where(x => x.UserId == users.Id).ToList();
            if (cartDetails.Count == 0)
            {
                CartDetails cartDetail = new CartDetails()
                {
                    Id = Guid.NewGuid(),
                    UserId = users.Id,
                    ProductId = IdPro,
                    Quantity = 1,
                };
                cartDetailServices.Add(cartDetail);
            }
            else 
            {
                CartDetails cartDetail = new CartDetails();
                cartDetail = cartDetailServices.GetAllCartDetails().FirstOrDefault(x => x.UserId == users.Id && x.ProductId == IdPro);
                cartDetail.Quantity = cartDetail.Quantity + 1;
                cartDetailServices.Update(cartDetail);
                
            }
            return RedirectToAction("Cart");
        }
    }
}

Assignment_ThangNVPH25980/Controllers/LoginController.cs
using Assignment_ThangNVPH25980.IService;
using Assignment_ThangNVPH25980.Models;
using Assignment_ThangNVPH25980.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Assignment_ThangNVPH25980.Controllers
{
    public class LoginController : Controller
    {
        private readonly IAccountServices accountServices;
        public LoginController()
        {
            accountServices = new AccountServices();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string user, string pass )
        {
            List<Accounts> a=accountServices.GetAllAccounts().Where(x=>x.UserName==user && x.Password==pass).ToList();
            HttpContext.Session.SetString("User",JsonConvert.SerializeObject(a));
            if (a.Count() > 0)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SignUp(Accounts accounts)
        {
            if (accountServices.Add(accounts))
                return RedirectToAction("Login");
            else return BadRequest();
        }
    }
}

Assignment_ThangNVPH25980/Controllers/ManagementController.cs
using Assignment_ThangNVPH25980.IServices;
using Assignment_ThangNVPH25980.Models;
using Assignment_ThangNVPH25980.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace Assignment_ThangNVPH25980.Views
{
    public class ManagementController : Controller
    {
        private readonly IProductServices productServices;
        private readonly OuteDBContext context;
        private readonly IColorServices colorServices;
        private readonly ISizeServices sizeServices;
        private readonly ICategoryServices categoryServices;
        private readonly IProductDetailServices productDetailServices;
        public ManagementController()
        {
            productServices=new ProductServices();
            context=new OuteDBContext();
            colorServices=new ColorServices();
            sizeServices=new SizeServices();    
            categoryServices=new CategoryServices();    
            productDetailServices=new ProductDetailServices();
        }
        public IActionResult Index()
        {
            return View();
        } 
        public IActionResult ProductList()
        {
            List<Products> products = productServices.GetAllProducts();
            ViewBag.Products = products;
            var lst = context.Products.Include("Category").ToList();
            return View(lst);
            
        }
        public IActionResult Details(Guid Id)
        {
            OuteDBContext context = new OuteDBContext();
            var product = context.Products.Include("Size").Include("Color").Include("Category").FirstOrDefault(x => x.Id == Id);
            return View(product);
        }
        #region AddProduct
        public IActionResult AddProduct()
        {
            List<Color> colors = colorServices.GetAllColor();
            List<Size> sizes = sizeServices.GetAllSize();
            List<Category> categories = categoryServices.GetAllCategory();
            ViewBag.Colors = colors;
            ViewBag.Sizes = sizes;
            ViewBag.Categories = categories;
            return View();
        }
        //public IActionResult DetailProduct(Guid Id)
        //{
        //    var product = context.Products.Find(Id);
        //    return View(product);
        //}

        [HttpPost]
        public IActionResult AddProduct(Products products, [Bind] IFormFile ImageFile)
        {
            var x = ImageFile.FileName;
            if (ImageFile != null && ImageFile.Length > 0)
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", ImageFile.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    ImageFile.CopyTo(stream);
                }
            }
            products.Image = ImageFile.FileName;
            if (productServices.Add(products))
                return RedirectToAction("ProductList");
            else return BadRequest();
        }
        #endregion

        [HttpGet]
        public IActionResult EditProduct(Guid Id)
        {
            List<Color> colors = colorServices.GetAllColor();
            List<Size> sizes = sizeServices.GetAllSize();
            List<Category> categories = categoryServices.GetAllCategory();
            ViewBag.Colors = colors;
            ViewBag.Sizes = sizes;
            ViewBag.Categories = categories;
            var product = productServices.GetProductsById(Id);
            return View(product);
        }

        public IActionResult EditProduct(Products p, [Bind] IFormFile ImageFile)
        {
            var x = ImageFile.FileName;
            if (ImageFile != null && ImageFile.Length > 0)
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", ImageFile.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    ImageFile.CopyTo(stream);
                }
            }
            p.Image = ImageFile.FileName;
            if (productServices.Update(p))
                return RedirectToAction("ProductList");
            else return BadRequest();
        }
        [HttpGet]
        public IActionResult ShowListProdcutDetail(Guid Id)
        {
            List<ProductDetails> products = context.ProductDetails.Where(x=>x.ProductId==Id).Include("Color").Include("Size").Include("Products").ToList();
            ViewBag.ProductDetails=products;
            return View();
        }
        //
        //public IActionResult ShowListProdcutDetail(Guid Id)
        //{

        //}

        [HttpGet]
        public IActionResult AddProductDetail(Guid Id)
        {
            List<Size> sizes = sizeServices.GetAllSize();
            List<Color> colors=colorServices.GetAllColor();
            ViewBag.Sizes=sizes;
            ViewBag.Color=colors;
            var p=productServices.GetProductsById(Id);
            return View(p);
        }
        [HttpPost]
        public IActionResult AddProductDetail(ProductDetails productDetails,Guid Id)
        {
            productDetails.ProductId= Id;
            if (productDetailServices.Add(productDetails))
            {
                return RedirectToAction("AddProduct");
            }
            return View();
        }
        [HttpGet]
        public IActionResult UpdateProductDetail(Guid Id)
        {
            var p = productDetailServices.GetProductDetailsById(Id);
            return View(p);
        }
        public IActionResult UpdateProductDetail(ProductDetails productDetails)          
        {
            if (productDetailServices.Update(productDetails))
            {
                return RedirectToAction("ShowListProdcutDetail");
            }
            return View();
        }

        public IActionResult DeleteProduct(Guid Id)

        {   if (productServices.Delete(Id))
            {
                return RedirectToAction("ProductList");
            }
            return View();
        }

        public IActionResult DeleteTest(Guid Id)
        {
            Products a = productServices.GetProductsById(Id);
            HttpContext.Session.SetString("delete", JsonConvert.SerializeObject(a));
            if (productServices.Delete(Id))
            {
                return RedirectToAction("ProductList");
            }
            return View();
        }
        public IActionResult RollBack()
        {
            string json = HttpContext.Session.GetString("delete");
            var pro=JsonConvert.DeserializeObject<Products>(json);
            if (productServices.Add(pro))
            {
                return RedirectToAction("ProductList");
            }
            return View();
        }

    }
}

Assignment_ThangNVPH25980/Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="container giaban">
<h4>Trang chủ > Giới thiệu>></h4>
<hr style="border: 2px solid orangered;">   
</div>

<div class="container " style="margin-top: 50px;">
<div class="row " >
  <div class="col-md-3 " >
      <hr style="border: 1px solid orangered;"> 
      <h3 >DANH MỤC TRANG</h3>
      <hr style="border: 1px solid orangered;"> 
      <div class="danhmuc" style="border: 2px solid black;" >
          <ul >
              <li>
                  <a href=""  >TRANG CHỦ</a>
              </li>
              <li>
                  <a href=""  >SẢN PHẨM</a>
              </li>
              <li>
                  <a href=""  >BẢNG SIZE</a>
              </li>
              <li>
                  <a href=""  >GIỎ HÀNG</a>
              </li>
              <li>
                  <a href=""  >GIỚI THIỆU</a>
              </li>
          </ul>
      </div>
  </div>
  <div class="col-md-9">
      <div class="row">
          <p class="title">GIỚI THIỆU</p>
          <p class="title">OUTERITY XIN CHÀO CÁC CẬU!</p>
          <p class="title1">
              OURTERITY là thương hiệu thời trang nam dành cho giới trẻ theo phong cách Hàn Quốc.
              Được thành lập tới nay được 6 năm, OURTERITY đã và đang dần trở thành một người bạn 
              gần gũi, tin cậy và đầy mới mẻ của giới trẻ Việt trong câu chuyện ăn mặc, 
              với Fanpage Facebook đạt gần 450.000 lượt thích, group fan cứng hơn 18.000 thành viên,
               kênh Tiktok gần 250.000 lượt folllow.
          </p>
          <video src="~/css/videogt.mp4"  controls ></video>
          <p class="title1">OURTERITY mang đến những bộ trang phục cho khách hàng trẻ có lối sống năng động, hiện đại,
          thích trải nghiệm, lạc quan từ bên trong tâm hồn, phong cách sống lẫn gu ăn mặc. 
          Khi mặc những sản phẩm của OURTERITY, quan trọng nhất là các cậu vui vẻ, thoải mái được là 
          chính mình theo đuổi những điều mình mong muốn. </p>
          <img src="~/css/gt1.jfif" alt="">
          <p class="title1">
              OURTERITY nổi bật với: <br>
              1. Sự đa dạng: Với đầy đủ các sản phẩm từ quần áo tới các loại phụ kiện từ đầu đến chân, với nhiều dòng sản phẩm đáp ứng được cả nhu cầu đi học, đi chơi, đi làm. <br>
              2. Sự mới mẻ: OURTERITY ra mắt các Bộ sưu tập sản phẩm mới liên tục trong tháng. <br>
              3. Giá cả hợp lý với chất lượng, phù hợp cho các bạn học sinh, sinh viên.
          </p>
          <p class="title1">
              CAM KẾT MUA HÀNG TẠI OURTERITY
              Hỗ trợ đổi hàng trong 7 ngày <br>
              Giao hàng nhanh chóng, nhận hàng được kiểm tra hàng trước khi thanh toán <br>
              Có hình ảnh thật 100% giống mô tả <br>
              Đặt hàng nhanh chóng, tư vấn nhiệt tình 
          </p>
          <img src="~/css/gt2.jfif" alt="">
      </div>

</div>
</div>
</div>

Assignment_ThangNVPH25980/Views/Home/Bill.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<Assignment_ThangNVPH25980.Models.Bill>

<div class="table-wrapper" style="max-height: 500px; overflow-y: scroll;">
    <div style="margin-top=30px">
        <h2>Quản lý sản phẩm</h2>
    </div>

@*    <div style="margin: 20px 0px 20px 0px">
        <a href="@Url.Action("AddProduct","Management",new{})" style="text-decoration:none; color: white">
            <button type="button" class="btn btn-success"><i class="fa-sharp fa-solid fa-layer-plus"></i>  Add new</button>
        </a>
    </div>*@
    <table class="table tablePR" style="font-size: 10pt; text-align: center; overflow-y: scroll; max-height: 700px;">
        <thead>
            <tr>
                <th scope="col">STT</th>
                <th scope="col">Người mua</th>
                <th scope="col">Ngày mua</th>
                <th scope="col">Tình trạng</th>
                <th scope="col">Tổng tiền</th>
                <th scope="col">Chức năng</th>
            </tr>
        </thead>
        <tbody style="font-size: 10pt; text-align: center;line-height: 100px;">
            @{
                int count = 1;
            }
            @foreach (var a in  ViewBag.Bills )
            {
                <tr>
                    <th>@(count++)</th>
                    <th>
                        <a href="@Url.Action("BillDetail","Home",new{billId=a.Id})" style="text-decoration:none; color: white">
                           @a.Accounts.UserName
                        </a>
                    </th>
                    <th>@a.CreatedDate</th>
                    <th>@(a.Status==0?"Đã huỷ":a.Status==1?"Đang giao ":"Thành công")</th>
                    <th></th>>
                    <th>
                        <a href="@Url.Action("UpdateBillDetail","Home",new{Id=a.Id})" style="text-decoration:none; color: white">
                            <button type="button" class="btn btn-danger" style="font-size: 10pt;float: right;margin-top: 40px; ">
                                <i class="fa-regular fa-trash-can"></i>
                            </button>
                        </a>
                        <a href="@Url.Action("UpdateBillDetail","Home",new{Id=a.Id})" style="text-decoration:none; color: white">
                            <button type="button" class="btn btn-warning" style="font-size: 10pt;float: right; margin: 40px 5px;">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </button>
                        </a>

                    </th>

                </tr>


            }

        </tbody>
    </table>
</div>

Assignment_ThangNVPH25980/Views/Home/BillDetail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    List<ProductDetails> products = ViewBag.Products;
}

@model IEnumerable<Assignment_ThangNVPH25980.Models.BillDetails>

<div class="table-wrapper" style="max-height: 500px; overflow-y: scroll;">
    <div style="margin-top:30px">
        <h2>Chi tiết hoá đơn </h2>
    </div>

@*    <div style="margin: 20px 0px 20px 0px">
        <a href="@Url.Action("AddProduct","Management",new{})" style="text-decoration:none; color: white">
            <button type="button" class="btn btn-success"><i class="fa-sharp fa-solid fa-layer-plus"></i>  Add new</button>
        </a>
    </div>*@
    <table class="table tablePR" style="font-size: 10pt; text-align: center; overflow-y: scroll; max-height: 700px;">
        <thead>
            <tr>
                <th scope="col">STT</th>
                <th scope="col">Ảnh</th>
                <th scope="col">Sản phẩm</th>
                <th scope="col">Size</th>
                <th scope="col">Color</th>
                <th scope="col">Số lượng</th>
                <th scope="col">Thành tiền</th>
                <th scope="col">Chức năng</th>
            </tr>
        </thead>
        <tbody style="font-size: 10pt; text-align: center;line-height: 100px;">
            @{
                int count = 1;             
                decimal total = 0;
            }
            @foreach (var a in  ViewBag.BillDetail)
            {
                <tr>
                    <th>@(count++)</th>
                    
                    <th>
                        <a @*href="@Url.Action("Details","Management",new{Id=a.Id})"*@ style="text-decoration:none; color: white">
                           <img style="width:100px;height: 100px;" src="~/images/@a.ProductDetails.Products.Image"  />
                        </a>
                    </th>
                    <th>@a.ProductDetails.Products.Name</th>
                    <th>@a.ProductDetails.Size.Name</th>
                    <th>@a.ProductDetails.Color.Name</th>
                    <th>@a.Quantity</th>
                    <th>@(a.ProductDetails.Products.Price*a.Quantity)</th>
                    <th></th>>
                    <th>
                        <a href="@Url.Action("DeleteProduct","Management",new{Id=a.Id})" style="text-decoration:none; color: white">
                            <button type="button" class="btn btn-danger" style="font-size: 10pt;float: right;margin-top: 40px; ">
                                <i class="fa-regular fa-trash-can"></i>
                            </button>
                        </a>
                        <a href="@Url.Action("EditProduct","Management",new{Id=a.Id})" style="text-decoration:none; color: white">
                            <button type="button" class="btn btn-warning" style="font-size: 10pt;float: right; margin: 40px 5px;">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </button>
                        </a>

                    </th>
                    @{
                            total+=(a.ProductDetails.Products.Price * a.Quantity);
                        }

                </tr>


            }

        </tbody>
    </table>
</div>

Assignment_ThangNVPH25980/Views/Home/Cart.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    List<Products> Products = ViewBag.Products;
    List<ProductDetails> lstPro = ViewBag.Pro;
    List<CartDetails> cartDetails = ViewBag.CartDetail;

}
@*@model IEnumerable<Assignment_ThangNVPH25980.Models.CartDetails>;*@

<div class="container giaban">
    <h4>Trang chủ > Giỏ hàng>></h4>
    <hr style="border: 2px solid orangered;">
</div>


<div class="container ">
    <center><p class="tieude">Giỏ hàng của bạn</p></center>
            <form asp-action="PayToBill">
    <div class="row thanhtoan">

        <div class="col-md-8">
            @{
                decimal total = 0;
            }
            @foreach (var a in ViewBag.CartDetail)
            {
                <div class="row">
                    <div class="col-md-2"><img src="/images/@a.ProductDetails.Products.Image" class="image" alt="..."></div>
                    <div class="col-md-10">
                        <h4>@a.ProductDetails.Products.Name</h4>  
                        <a href="@Url.Action("Delete","Home" ,new{Id=@a.Id})">
                        <button type="button" class="btn btn-secondary" style="margin-left: 600px; width: 30px; height: 30px;font-size: 15px;">
                            <i class="fa-solid fa-trash-can"></i></button></a>
                        <h5>@a.ProductDetails.Products.Price<del>(230.000 đ)</del></h5>
                        <h5 style="padding-top: 10px;">@a.ProductDetails.Size.Name- @a.ProductDetails.Color.Name</h5>
                        <button><i class="fa-solid fa-minus"></i></button>
                        <button>@a.Quantity</button>
                        <button><i class="fa-solid fa-plus"></i></button>
                        <h5 style="padding-left:550px;color: red;">@(a.ProductDetails.Products.Price*a.Quantity) </h5>
                        @{
                            total+=a.ProductDetails.Products.Price * a.Quantity;
                        }
                    </div>
                </div>
            }

            <hr class="hrgh">

            <div class="row">
                <div class="mb-3">

                    <h5>Ghi chú</h5>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>
            </div>
        </div>
        <div class="col-md-4 thanhtoan1">
            <h4>Thông tin thanh toán  (@cartDetails.Count() )</h4>
            <hr style="color:black;">
            <div class="row">
                <div class="col-md-6"><h5>Tổng tiền</h5></div>
                <div class="col-md-6" style="color: red;"><h5 name="PriceTotal">@total đ</h5></div>

            </div>
            <hr style="color:black;">
            <h6>Phí vận chuyển sẽ được tính ở trang thanh toán.</h6>
            <h6>Bạn cũng có thể nhập mã giảm giá ở trang thanh toán</h6>
            <a href="@Url.Action("PayToBill","Home",new{})"></a>
            <button type="submit" class="btn_thanhtoan">Thanh toán</button>
        </div>
    </div>
    </form>
</div>

Assignment_ThangNVPH25980/Views/Home/Login.cshtml
@model Assignment_ThangNVPH25980.Models.Accounts;
<div class="container giaban">
      <h4>Trang chủ > Đăng nhập>></h4>
      <hr style="border: 2px solid orangered;">   
    </div>
    

      <div class="Login full">
        <div class=" container container1">
          <div class="form login">
            <span class="title">Login</span>
              <form asp-action="Login">
                <div class="input-field" >
                  <input type="text" placeholder="Email" asp-for="UserName" name="user">
                  <i class="fa-regular fa-envelope icon"></i>
                </div>
                <div class="input-field">
                  <input type="password" placeholder="Password" asp-for="Password" name="pass">
                  <i class="fa-solid fa-lock icon"></i>
                  <i class="fa-regular fa-eye-slash showHidePW"></i>
                </div>

                <div class="checkbox-text">
                  <div class="checkbox-content">
                    <input type="checkbox" id="logCheck">
                    <label for="logCheck" class="text">Remeber me</label>
                  </div>
                  <a href="#" class="text">Quên mật khẩu?</a>
                </div>

                <div class="input-field button">
                  <input type="submit" value="Đăng nhập">
                  
                </div>
              </form>

              <div class="login-signup">
                <span class="text">Bạn chưa có tài khoản?
                  <a href="@Url.Action("SignUp","Home",new{})"  style="text-decoration:none; color: white" class="text signup-text" class="text signup-text">Đăng ký</a>
                </span>
              </div>

          </div>
        </div>
      </div>


@*
      <div class="center">
      <h1>Login</h1>
      <form method="post">
        <div class="txt_field">
          <input type="text" required>
          <span></span>
          <label>Username</label>
        </div>
        <div class="txt_field">
          <input type="password" required>
          <span></span>
          <label>Password</label>
        </div>
        <div class="pass">Forgot Password?</div>
        <input type="submit" value="Login">
        <div class="signup_link">
          Not a member? <a href="#">Signup</a>
        </div>
      </form>
    </div>*@

Assignment_ThangNVPH25980/Views/Home/UpdateBillDetail.cshtml
@model Assignment_ThangNVPH25980.Models.Bill;
<form asp-action="UpdateBillDetail" style="margin-top: 30px; margin-bottom: 30px;" enctype="multipart/form-data">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
            </div>
            <div class="col-md-9">
                               <div class="mb-3 row" style=" font-size: 13pt;">
                    <label class="col-sm-2 col-form-label">Tình trạng</label>
                    <div class="col-sm-10">

                        <div class="btn-group" role="group" aria-label="Basic radio toggle button group">                       
                                <input asp-for="Status" type="radio" class="btn-check" name="Status" id="0" value="0">
                                <label asp-for="Status" class="btn btn-outline-primary" for="0">Đã huỷ</label>

                                <input asp-for="Status" type="radio" class="btn-check" name="Status" id="1" value="1">
                                <label asp-for="Status" class="btn btn-outline-primary" for="1">Đang giao hàng</label>

                                <input asp-for="Status" type="radio" class="btn-check" name="Status" id="2" value="2">
                                <label asp-for="Status" class="btn btn-outline-primary" for="2">Thành công</label>
                          
                            
                        </div>

                    </div>
                </div>
                </div>

                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-primary" />
                </div>

                <a href="@Url.Action("ProductList","Management",new{ })">
                    <button type="button" class="btn btn-success" style="width: 70px;height: 30px; font-size:13pt; margin-top:20px">
                        <i class="fa-solid fa-left-long"></i>
                    </button>
                </a>

            </div>
        </div>
    </div>
</form>